# Generated by Django 4.1.2 on 2022-10-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_web_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Web',
            new_name='Website',
        ),
    ]
